### ISSUE TITLE
Add BenchFlowMinioClient

### ISSUE THREAD

**Issue by simonedavico** [benchflow/commons#7]
We are using a simple `BenchFlowMinioClient` to manage our interaction with the minio database. Since we need to interact with minio from both the experiments-manager and the drivers-maker, it is better if we isolate our client and specify it as a dependency in both components.

**Features, among many others:**
- make it configurable (e.g., https://github.com/benchflow/drivers-maker/pull/22#discussion-diff-57162970)

**Comment by VincenzoFerme** [comment]
@simonedavico:
- create a folder `minio/java` and add a maven project in that folder
- release it as a `jar` as it is done for the `benchflow-keyname-hash-generator`

Working on that, expose also a method to generate the hash we put in front of the Minio key, using the `benchflow-keyname-hash-generator` library.
